{% set name = "kanaries-track" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kanaries_track-{{ version }}.tar.gz
  sha256: 0b154cd2acdd3dc96804fc05aea7579d043353917a5c74fee4d9028c79126f2c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - dateutils >=0.6.12
    - requests >=2.31.0
    - backoff >=2.2.1

test:
  imports:
    - kanaries_track
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/kanaries-track/
  summary: track to kanaries data infra
  description: track to kanaries data infra
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://pypi.org/project/kanaries-track/
  dev_url: https://github.com/Kanaries/kanaries-track

extra:
  recipe-maintainers:
    - longxiaofei
    - rxm7706
